---
# file: roles/php/tasks/main.yml
- name: remi repository
  package:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm

- name: php install
  yum:
    name: "{{ item }}-{{ php_version }}"
    enablerepo: "{{ php_repo }}"
  with_items:
    - php
    - php-mbstring
